server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?seUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  thymeleaf:
    mode: html
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 123456
      connect-timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.edu.xcu.springboot.security.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-prefix: t_

token:
  signkey: Qww3bG076BRviMKYShat2T8LH217Mi1aBQmD3X16smHkhjWkceM3IesiXAFkO0MH
  expiration: 3600000
